'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Icons } from '@/components/ui/icons';

export function AboutSheet() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <Sheet open={isOpen} onOpenChange={setIsOpen}>
      <SheetTrigger asChild>
        <Button variant="ghost" size="icon">
          <Icons.Info className="h-6 w-6" />
        </Button>
      </SheetTrigger>
      <SheetContent className="w-full sm:max-w-md" onOpenAutoFocus={(e) => e.preventDefault()}>
        <SheetHeader>
          <SheetTitle>About TimeWise</SheetTitle>
          <SheetDescription>Learn more about the project and the developer.</SheetDescription>
        </SheetHeader>
        
        <div className="py-6 text-sm text-foreground space-y-6">
            <div className="space-y-2">
            <h3 className="font-semibold text-lg font-headline">The Human Behind the Curtain</h3>
            <p>
                Hey there! I'm <span className="font-bold text-primary">Mitul Parmar</span>, a Python backend and AI/ML
                developer with a knack for building cool things. I also know my way around a Nest.js backend and a React
                front-end.
            </p>
            <p>
                I live for backend logic and AI models — the serious, sensible part of the stack. Front-end? That’s where
                things get weird. I don’t usually mess with pixels and padding, but I let an AI drag me through it.
                Somehow, we survived — and yes, every button that looks slightly off is probably AI’s fault. Or mine.
                Probably both.
            </p>
            </div>
            <div className="space-y-2">
            <h3 className="font-semibold text-lg font-headline">About the Project</h3>
            <p>
                Think of TimeWise as a grand experiment. What happens when a developer teams up with an AI? This project
                is the answer. About 90% of the code you see was generated by an AI, guided by my prompts. The other 10%
                is me fixing the weird stuff the AI does.
            </p>
            <p>
                This app is <span className="font-semibold">100% client-side</span>, meaning all your data stays right
                here in your browser. It's also open source, so feel free to peek at the code, suggest changes, or just
                marvel at what a human-AI pair can build.
            </p>
            </div>
            <div className="space-y-3">
            <h3 className="font-semibold text-lg font-headline">Connect & Contribute</h3>
            <div className="flex gap-2">
                <Button asChild variant="outline" className="w-full">
                <a href="https://www.linkedin.com/in/mitulparmar11/" target="_blank" rel="noopener noreferrer">
                    <Icons.Linkedin className="mr-2" />
                    LinkedIn
                </a>
                </Button>
                <Button asChild variant="outline" className="w-full">
                <a href="https://github.com/mitulparmar7161/time-wise.git" target="_blank" rel="noopener noreferrer">
                    <Icons.Github className="mr-2" />
                    GitHub
                </a>
                </Button>
            </div>
            </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}