'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Icons } from '@/components/ui/icons';
import { useGitHubContributors } from '@/hooks/use-github-contributors';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';

interface AboutSheetProps {
  isOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function AboutSheet({ isOpen: externalIsOpen, onOpenChange }: AboutSheetProps = {}) {
  const [internalIsOpen, setInternalIsOpen] = useState(false);
  const { contributors, loading, error } = useGitHubContributors('mitulparmar7161', 'time-wise');
  
  const isOpen = externalIsOpen ?? internalIsOpen;
  const setIsOpen = onOpenChange ?? setInternalIsOpen;

  return (
    <Sheet open={isOpen} onOpenChange={setIsOpen}>
      <SheetTrigger asChild>
        <Button variant="ghost" size="icon">
          <Icons.Info className="h-6 w-6" />
        </Button>
      </SheetTrigger>
      <SheetContent className="w-full sm:max-w-md" onOpenAutoFocus={(e) => e.preventDefault()}>
        <SheetHeader>
          <SheetTitle>About TimeWise</SheetTitle>
          <SheetDescription>Learn more about the project and the developer.</SheetDescription>
        </SheetHeader>
        
        <div className="py-6 text-sm text-foreground space-y-6">
            <div className="space-y-2">
            <h3 className="font-semibold text-lg font-headline">The Human Behind the Curtain</h3>
            <p>
                Hey there! I'm <span className="font-bold text-primary">Mitul Parmar</span>, a Python backend and AI/ML
                developer with a knack for building cool things. I also know my way around a Nest.js backend and a React
                front-end.
            </p>
            <p>
                I live for backend logic and AI models — the serious, sensible part of the stack. Front-end? That’s where
                things get weird. I don’t usually mess with pixels and padding, but I let an AI drag me through it.
                Somehow, we survived — and yes, every button that looks slightly off is probably AI’s fault. Or mine.
                Probably both.
            </p>
            </div>
            <div className="space-y-2">
            <h3 className="font-semibold text-lg font-headline">About the Project</h3>
            <p>
                Think of TimeWise as a grand experiment. What happens when a developer teams up with an AI? This project
                is the answer. About 90% of the code you see was generated by an AI, guided by my prompts. The other 10%
                is me fixing the weird stuff the AI does.
            </p>
            <p>
                This app is <span className="font-semibold">100% client-side</span>, meaning all your data stays right
                here in your browser. It's also open source, so feel free to peek at the code, suggest changes, or just
                marvel at what a human-AI pair can build.
            </p>
            </div>
            <div className="space-y-3">
            <h3 className="font-semibold text-lg font-headline">Connect & Contribute</h3>
            <div className="flex gap-2">
                <Button asChild variant="outline" className="w-full">
                <a href="https://www.linkedin.com/in/mitulparmar11/" target="_blank" rel="noopener noreferrer">
                    <Icons.Linkedin className="mr-2" />
                    LinkedIn
                </a>
                </Button>
                <Button asChild variant="outline" className="w-full">
                <a href="https://github.com/mitulparmar7161/time-wise.git" target="_blank" rel="noopener noreferrer">
                    <Icons.Github className="mr-2" />
                    GitHub
                </a>
                </Button>
            </div>
            </div>
            
            <Separator />
            
            <div className="space-y-3">
            <h3 className="font-semibold text-lg font-headline">Contributors</h3>
            {loading ? (
                <div className="flex items-center justify-center py-4">
                <Icons.Loader className="h-6 w-6 animate-spin text-muted-foreground" />
                <span className="ml-2 text-sm text-muted-foreground">Loading contributors...</span>
                </div>
            ) : error ? (
                <div className="text-sm text-destructive py-4">{error}</div>
            ) : contributors.length > 0 ? (
                <ScrollArea className="h-48">
                <div className="space-y-3">
                    {contributors.map((contributor) => (
                    <a
                        key={contributor.id}
                        href={contributor.html_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-3 p-2 rounded-lg hover:bg-secondary/50 transition-colors group"
                    >
                        <Avatar className="h-10 w-10">
                        <AvatarImage src={contributor.avatar_url} alt={contributor.login} />
                        <AvatarFallback>{contributor.login.slice(0, 2).toUpperCase()}</AvatarFallback>
                        </Avatar>
                        <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-foreground group-hover:text-primary truncate">
                            {contributor.login}
                        </p>
                        <p className="text-xs text-muted-foreground">
                            {contributor.contributions} contributions
                        </p>
                        </div>
                        <Icons.Github className="h-4 w-4 text-muted-foreground group-hover:text-foreground" />
                    </a>
                    ))}
                </div>
                </ScrollArea>
            ) : (
                <div className="text-sm text-muted-foreground py-4">No contributors found</div>
            )}
            </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}